service: dio-live-serveless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamod:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:us-east-1:931363792652:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/handler.insertItem # ou src/insertItem.handler?
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/handler.fetchItems # ou src/fetchItems.handler?
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: src/handler.fetchItem # ou src/fetchItem.handler?
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/handler.updateItem # ou src/updateItems.handler?
    events:
      - http:
          path: /items/{id}
          method: put

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ItemTableNew
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH


